### ISSUE TITLE
Multiple Midi files

### ISSUE THREAD

**Issue by Titaniumtown** [KrystilizeNevaDies/CuberiteMidiPlayer#1]
Is there a plan to implement multiple midi files? Like a separate folder or something?

**Comment by KrystilizeNevaDies** [comment]
Yea, I'll implement that tonight, And I'll see what I can do about using straight midi files

**Comment by Titaniumtown** [comment]
Yay! :)

**Comment by KrystilizeNevaDies** [comment]
added in 77f58ff
Also included some songs that work decently, and improved the tempo calculations
